ALTER TABLE crop_diagnoses
  ADD COLUMN IF NOT EXISTS globally_closed_at TIMESTAMPTZ DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS globally_closed_by UUID DEFAULT NULL REFERENCES users(id) ON DELETE SET NULL;
